exports.states_lists = {
    'BJ' : { // Benin
        'AT' : 'Atakora',
        'AL' : 'Alibori',
        'AT' : 'Atlantique',
        'BG' : 'Borgou',
        'CO' : 'Collines',
        'DO' : 'Donga',
        'KO' : 'Couffo',
        'LI' : 'Littoral',
        'MO' : 'Mono',
        'OU' : 'Ouémé',
        'PL' : 'Plateau',
        'ZO' : 'Zou'
    },

    'CI' : { // Côte d'Ivoire
        'AB' : 'Abidjan',
        'BS' : 'Bas-Sassandra',
        'CM' : 'Comoé',
        'DN' : 'Denguélé',
        'GD' : 'Gôh-Djiboua',
        'LC' : 'Lacs',
        'LG' : 'Lagunes',
        'MG' : 'Montagnes',
        'SM' : 'Sassandra-Marahoué',
        'SV' : 'Savanes',
        'VB' : 'Vallée du Bandama',
        'WR' : 'Woroba',
        'YM' : 'Yamoussoukro',
        'ZZ' : 'Zanzan'
    },

    'BF': { //Burkina Faso
        'bale': "Balé",
        'banwa': "Banwa",
        'kossi': "Kossi",
        'mouhoun': "Mounhoun",
        'nayala': "Nayala",
        'sourou': "Sourou",
        'comoe': "Comoé",
        'leraba': "Léréba",
        'kadiogo': "Kadiogo",
        'boulgou': "Boulgou",
        'koulpego': "Koulpégo",
        'kouritenga': "Kouritenga",
        'bam': "Bam",
        'namentaga': "Namentaga",
        'sanmatenga': "Sanmatenga",
        'boulkiemde': 'Boulkiemde',
        'sanguie': 'Sanguié',
        'sissili': 'Sissili',
        'ziro': "Ziro",
        'bazega': "Bazéga",
        'nahouri': "Nahouri",
        'zoundwéogo': "Zoundwéogo",
        'gnagna': "Gnagna",
        'gourma': "Gourma",
        'komondjari': "Komondjari",
        'kompiega': "Kompiega",
        'tapoa': "Tapoa",
        'houet': "Hoeut",
        'kenedougou': "Kénédougou",
        'tuy': "Tuy",
        'loroum': "Loroum",
        'passore': "Passoré",
        'yatenga': "Yatenga",
        'zondoma': "Zondoma",
        'ganzourgou': "Ganzourgou",
        'kourweogo': "Kourweogo",
        'oubritenga': "Oubritenga",
        'oudalan': "Oudalan",
        'seno': "Séno",
        'soum': "Soum",
        'yagha': "Yagha",
        'bougouriba': "Bougouriba",
        'ioba': "Ioba",
        'noumbiel': "Noumbiel",
        'poni': "Poni"
    },

    'TG': { // TOGO
        'GF1':'Golfe 1',
        'GF2':'Golfe 2',
        'GF3':'Golfe 3',
        'GF4':'Golfe 4',
        'GF5':'Golfe 5',
        'GF6':'Golfe 6',
        'GF7':'Golfe 7',
        'AN1':'Agoé-Nyivé 1',
        'AN2':'Agoé-Nyivé 2',
        'AN3':'Agoé-Nyivé 3',
        'AN4':'Agoé-Nyivé 4',
        'AN5':'Agoé-Nyivé 5',
        'AN6':'Agoé-Nyivé 6',
        'ZI1': 'Zio 1',
        'ZI2': 'Zio 2',
        'ZI3': 'Zio 3',
        'ZI4': 'Zio 4',
        'LC1': 'Lacs 1',
        'LC2': 'Lacs 2',
        'LC3': 'Lacs 3',
        'LC4': 'Lacs 4',
        'VO1': 'Vo 1',
        'VO2': 'Vo 2',
        'VO3': 'Vo 3',
        'VO4': 'Vo 4',
        'YT1':'Yoto 1',
        'YT2':'Yoto 2',
        'YT3':'Yoto 3',
        'CK1':'Cinkassé 1',
        'CK':'Cinkassé ',
        'TN1':'Tone 1',
        'TN2':'Tone 2',
        'TN3':'Tone 3',
        'TN4':'Tone 4',
        'KJ1':'Kpendjal 1',
        'KJ2':'Kpendjal 2',
        'KJO1':'Kpendjal Ouest 1',
        'KJO2':'Kpendjal Ouest 2',
        'OI1' : 'Oti 1',
        'OI2' : 'Oti 2',
        'OIS1' : 'Oti Sud 1',
        'OIS2' : 'Oti Sud 2',
        'TD1' : 'Tandjouare 1',
        'TD2' : 'Tandjouare 2',
        'TD3' : 'Tandjouare 3',
        'KR1' : 'Keran 1',
        'KR2' : 'Keran 2',
        'KR3' : 'Keran 3',
        'BS1' : 'Bassar 1',
        'BS2' : 'Bassar 2',
        'BS3' : 'Bassar 3',
        'BS4' : 'Bassar 4',
        'DK1': 'Dankpen 1',
        'DK2': 'Dankpen 2',
        'DK3': 'Dankpen 3',
        'KZ1' : 'Kozah 1',
        'KZ2' : 'Kozah 2',
        'KZ3' : 'Kozah 3',
        'KZ4' : 'Kozah 4',
        'BN1' : 'Binah 1',
        'BN2' : 'Binah 2',
        'DF1' : 'Doufelgou 1',
        'DF2' : 'Doufelgou 2',
        'DF3' : 'Doufelgou 3',
        'AS1' : 'Assoli 1',
        'AS2' : 'Assoli 2',
        'AS3' : 'Assoli 3',
        'TD1' : 'Tchaoudjo 1',
        'TD2' : 'Tchaoudjo 2',
        'TD3' : 'Tchaoudjo 3',
        'TD4' : 'Tchaoudjo 4',
        'ST1' : 'Sotouboua 1',
        'ST2' : 'Sotouboua 2',
        'ST3' : 'Sotouboua 3',
        'MO1' : 'Mô 1',
        'MO2' : 'Mô 2',
        // 47 wikipedia 
    }
}
