exports.states_lists = {
    'BJ' : { // Benin
        'AT' : 'Atakora',
        'AL' : 'Alibori',
        'AT' : 'Atlantique',
        'BG' : 'Borgou',
        'CO' : 'Collines',
        'DO' : 'Donga',
        'KO' : 'Couffo',
        'LI' : 'Littoral',
        'MO' : 'Mono',
        'OU' : 'Ouémé',
        'PL' : 'Plateau',
        'ZO' : 'Zou'
    },

    'CIV' : { // Côte d'Ivoire
        'AB' : 'Abidjan',
        'BS' : 'Bas-Sassandra',
        'CM' : 'Comoé',
        'DN' : 'Denguélé',
        'GD' : 'Gôh-Djiboua',
        'LC' : 'Lacs',
        'LG' : 'Lagunes',
        'MG' : 'Montagnes',
        'SM' : 'Sassandra-Marahoué',
        'SV' : 'Savanes',
        'VB' : 'Vallée du Bandama',
        'WR' : 'Woroba',
        'YM' : 'Yamoussoukro',
        'ZZ' : 'Zanzan'
    },

    'BF': { //Burkina Faso
        'bale': "Balé",
        'banwa': "Banwa",
        'kossi': "Kossi",
        'mouhoun': "Mounhoun",
        'nayala': "Nayala",
        'sourou': "Sourou",
        'comoe': "Comoé",
        'leraba': "Léréba",
        'kadiogo': "Kadiogo",
        'boulgou': "Boulgou",
        'koulpego': "Koulpégo",
        'kouritenga': "Kouritenga",
        'bam': "Bam",
        'namentaga': "Namentaga",
        'sanmatenga': "Sanmatenga",
        'boulkiemde': 'Boulkiemde',
        'sanguie': 'Sanguié',
        'sissili': 'Sissili',
        'ziro': "Ziro",
        'bazega': "Bazéga",
        'nahouri': "Nahouri",
        'zoundwéogo': "Zoundwéogo",
        'gnagna': "Gnagna",
        'gourma': "Gourma",
        'komondjari': "Komondjari",
        'kompiega': "Kompiega",
        'tapoa': "Tapoa",
        'houet': "Hoeut",
        'kenedougou': "Kénédougou",
        'tuy': "Tuy",
        'loroum': "Loroum",
        'passore': "Passoré",
        'yatenga': "Yatenga",
        'zondoma': "Zondoma",
        'ganzourgou': "Ganzourgou",
        'kourweogo': "Kourweogo",
        'oubritenga': "Oubritenga",
        'oudalan': "Oudalan",
        'seno': "Séno",
        'soum': "Soum",
        'yagha': "Yagha",
        'bougouriba': "Bougouriba",
        'ioba': "Ioba",
        'noumbiel': "Noumbiel",
        'poni': "Poni"

    }
}